# Generated by Django 3.1.7 on 2021-03-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tkt_status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('IN-PROGRESS', 'In-Progress'), ('ON-HOLD', 'On-Hold'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=12),
        ),
    ]
