# Generated by Django 3.1.7 on 2021-03-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_tkt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
