# Generated by Django 3.1.7 on 2021-03-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assignment',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
